name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install
      run: |
       sudo apt-get update
       sudo apt-get install build-essential
       
    - name: build
      run: gcc hashtable.c -o hashtable
      
    - name: run
      run: ./hashtable

